secret_key_base: sMeKDC_nRqiUeBsGoQoFBb3jUwX1LqCAhcRZVGG_8W4
port: 3000
name: arctor

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://redis:6379"
database_url: "postgres://postgres:postgres@postgres:5432/arctor_development"
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
