name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Build
      run: crystal build -Dpreview_mt --error-trace --release src/arctor.cr
      id: build_main
    - name: Build Worker
      run: crystal build -Dpreview_mt --error-trace --release src/arctor_worker.cr
      id: build_worker